channels:
- conda-forge
dependencies:
- python=3.8.0
- pip<=24.2
- pip:
  - mlflow==2.16.0
  - cloudpickle==3.0.0
  - numpy==1.24.3
  - optuna==4.0.0
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.3.0
  - scipy==1.10.1
  - xgboost==2.1.1
name: mlflow-env
