version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: DockerFile.train
    volumes:
      - ./model_artifacts:/app/model_artifacts
    environment: 
      - train_experiment=TR
      - model_name=xgboost
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    command: ["python", "train.py"]

  serving:
    build:
      context: .
      dockerfile: DockerFile.serve
    ports:
      - "8000:8000"
    volumes:
      - ./model_artifacts:/app/model_artifacts
    environment: 
      - train_experiment=TR
      - model_name=xgboost
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    depends_on:
      - training